"""Initial schema with all physical features

Revision ID: 6c982538a32f
Revises: 
Create Date: 2025-11-14 14:04:30.701175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c982538a32f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('missing_date', sa.DateTime(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('location_detail', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age_now', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('face_shape', sa.String(), nullable=True),
    sa.Column('hair_style', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('clothing_description', sa.Text(), nullable=True),
    sa.Column('special_features', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_urls', sa.Text(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=True),
    sa.Column('photos_downloaded', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_persons_external_id'), 'missing_persons', ['external_id'], unique=True)
    op.create_index(op.f('ix_missing_persons_id'), 'missing_persons', ['id'], unique=False)
    op.create_index(op.f('ix_missing_persons_status'), 'missing_persons', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missing_persons_status'), table_name='missing_persons')
    op.drop_index(op.f('ix_missing_persons_id'), table_name='missing_persons')
    op.drop_index(op.f('ix_missing_persons_external_id'), table_name='missing_persons')
    op.drop_table('missing_persons')
    # ### end Alembic commands ###
